name: Build
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install docker
        run: >
          sudo apt update -y -qqq;
          sudo apt install -y bash;
          sudo ln -svf bash /bin/sh;
          sudo /bin/bash scripts/.clean-os.sh;
          sudo /bin/bash scripts/install_for_docker.sh;
          sudo /bin/bash scripts/install_docker.sh;

      - name: Build cryptsetup ub2204
        run: |
          sudo /bin/bash run-build-ub2204.sh
          sudo /bin/systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/*
      - name: Upload cryptsetup ub2204
        run: |
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          _cryptsetup_ver="$(sudo ls -1 /home/.tmp.cryptsetup/cryptsetup-* | sed -e 's|.*cryptsetup-||g' -e 's|-.*||g' | tail -n1)"
          sudo ls -lah /home/.tmp.cryptsetup/
          sudo ls -1 /home/.tmp.cryptsetup/cryptsetup-* | sudo xargs --no-run-if-empty -I '{}' sudo /bin/bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_cryptsetup_ver}" -k "${{ secrets.GITHUB_TOKEN }}"
